[workspace]

default-members=["takoc", "takolib"]

members = [
    "takolib",
    "takoc",
    "tako-webui",
    "tako-bench",
    "llamada-calculus",
]

[profile.test]
opt-level = 3

[profile.release]
debug = true
