[workspace]
resolver = "2"
default-members=["tako", "takolib", "llamada"]

members = [
    "better-std",
    "takolib",
    "tako",
    "takoweb",
    "takobench",
    "llamada",
]

[profile.test]
opt-level = 3

[profile.release]
debug = true
