[workspace]

default-members=["butter-graph", "takoc", "takolib", "llamada-calculus"]

members = [
    "takolib",
    "takoc",
    "tako-webui",
    "tako-bench",
    "llamada-calculus",
    "butter-graph",
]

[profile.test]
opt-level = 3

[profile.release]
debug = true
