[package]
name = "takoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tako = { path = "../" }
tokio = { version = "1.21", features = [ "full" ]}
log = "0.4"
