[package]
name = "takobench"
version = "0.2.0"
edition = "2021"

[features]
bench = ["criterion"]
default = []

[dependencies]
criterion = { version = "0.5.1", optional = true }
takolib = { version = "0.2.0", path = "../takolib" }
