==================
GADTs
==================
#!/usr/bin/env tako
// test: all

// A simple, untyped  implementation of S expressions.
SExpr: Type = struct.new(
  func: (args: [Value; n]),
  args: [SExpr; n],
  forall n: Int,
)

// A well typed, but little, language using GADTs.
Expr(
  SubExpr(R: AllowedType): Reference(Expr(SubExpr, R))=Expr,
  R: AllowedType,
  forall AllowedType = Integer|Boolean
) = gadt.new(

  // Control flow:
  if(
    cond: SubExpr(R=Boolean),
    then: SubExpr(R=T),
    else: SubExpr(R=T),
    forall T: AllowedType
  ): Expr(SubExpr, R=T),

  // Binary operations:
  or     (left:  SubExpr(R=Boolean), right: SubExpr(R=Boolean)): Expr(SubExpr, R=Boolean),
  and    (left:  SubExpr(R=Boolean), right: SubExpr(R=Boolean)): Expr(SubExpr, R=Boolean),
  add    (left:  SubExpr(R=Integer), right: SubExpr(R=Integer)): Expr(SubExpr, R=Integer),
  mul    (left:  SubExpr(R=Integer), right: SubExpr(R=Integer)): Expr(SubExpr, R=Integer),
  eq     (left:  SubExpr(R=Integer), right: SubExpr(R=Integer)): Expr(SubExpr, R=Boolean),

  // Constants:
  integer(value: Integer): Expr(SubExpr, R=Integer),
  boolean(value: Boolean): Expr(SubExpr, R=Boolean),
)
---


