==================
Integer literal
==================
1
---
(source_file (expression (number (int_literal))))

==================
Float literal
==================
1.0
---
(source_file (expression (number (float_literal))))

==================
Long int
==================
1_000_000_000
---
(source_file (expression (number (int_literal))))

==================
Long float
==================
1_000_000_000.000_000
---
(source_file (expression (number (float_literal))))
