==================
Integer literal
==================
1
---
(source_file (expression (number (int_literal))))

==================
Float literal
==================
1.0
---
(source_file (expression (number (float_literal))))

==================
Float literal with too many decimal points
==================
1.0.0
---
(source_file
  (expression
    (number
      (float_literal)))
  (ERROR
    (UNEXPECTED '.')))

==================
Long int
==================
1_000_000_000
---
(source_file (expression (number (int_literal))))

==================
Long float
==================
1_000_000_000.000_000
---
(source_file (expression (number (float_literal))))

==================
Hex
==================
0xff00
---
(source_file (expression (hex_literal)))

==================
Color
==================
#FF0000AA
---
(source_file (expression (color)))

==================
Color Mixed case
==================
#ff00aa
---
(source_file (expression (color)))

==================
Color wrong number of digits
==================
#ff00aaa
---
(source_file (expression (color)) (ERROR))
