==================
Simple Sum
==================
1+2+3

---
(source_file
    (binary_expression
        left: (binary_expression
            left: (number
                (int_literal))
            right: (number
                (int_literal))
        )
        right: (number
            (int_literal)
        )
    )
)

==================
Simple Sum with comments
==================
1/*one*/+2/*two*/+3/*three*/

/* Comment
/* Double comment */
/* Second double comment */
*/
---
(source_file
    (binary_expression
        left: (binary_expression
              left: (number (int_literal))
              (nesting_comment)
              right: (number (int_literal))
              )
        (nesting_comment)
        right: (number (int_literal)))
        (nesting_comment)
        (nesting_comment
          (nesting_comment)
          (nesting_comment)
        )
)

