[package]
name = "partable-parser"
version = "0.1.0"
edition = "2021"
homepage.workspace = true
repository.workspace = true

[dependencies]
static_assertions = "1.1"
strum = "0.26.3"
strum_macros = "0.26.4"
