[package]
name = "tako"
version = "0.2.0"
authors = ["J Pratt <jp10010101010000@gmail.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE.md", "README.md"]

[features]
#default=["llvm_backend", "native"]
default=["native"]
wasm=["wasm-logger"]
native=["env_logger"]
llvm_backend=["inkwell", "backend"]
mlir_backend=["melior", "backend"]
backend=[] # signals that 'a' backend is active.

[lib]
name = "tako"
path = "src/lib.rs"

# [[bin]]
# name = "make_test_case"
# path = "tests/bins/make_test_case.rs"

# [[bench]]
# name = "tako_bench"
# harness = false

[dependencies]
thiserror = "1.0"
bitvec = "1"
log = "0.4"
pretty_assertions = "1.0"
futures = "0.3"
tokio = { version = "1.21", features = ["sync", "macros", "rt"] }
async-trait = "0.1"
# Info: https://nnethercote.github.io/2021/12/08/a-brutally-effective-hash-function-in-rust.html
fxhash = "0.2"
static_assertions = "1.1"
num-traits = "0.2"
enum-kinds = "0.5"
lazy_static = "1.4.0"
env_logger = { version = "0.9", optional = true }
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm15-0"], optional = true }
wasm-logger = { version = "0.2.0", optional = true }
melior = { version = "0.3.1", optional = true }

[dev-dependencies]
strum = "0.24"
strum_macros = "0.24"
pretty_assertions = "1.0"
rand = "0.8"
