[package]
name = "tako"
version = "0.2.0"
authors = ["J Pratt <jp10010101010000@gmail.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE.md", "README.md"]

[features]
wasm=[]
native=[]

[lib]
name = "tako"
path = "src/lib.rs"

[[bin]]
name = "make_test_case"
path = "tests/bins/make_test_case.rs"

# [[bench]]
# name = "tako_bench"
# harness = false

[dependencies]
thiserror = "1.0"
bitvec = "1"
log = "0.4"
env_logger = "0.9"
pretty_assertions = "1.0"
futures = "0.3"
tokio = { version = "1.21", features = ["sync", "macros", "io-util", "rt", "time"] }
async-trait = "0.1"
# Info: https://nnethercote.github.io/2021/12/08/a-brutally-effective-hash-function-in-rust.html
fxhash = "0.2"
static_assertions = "1.1"
num-traits = "0.2"
enum-kinds = "0.5"

[dev-dependencies]
strum = "0.24"
strum_macros = "0.24"
pretty_assertions = "1.0"
rand = "0.8"
