name: Check and upload takoc

on: [push]

env:
  CARGO_TERM_COLOR: always
  LLVM_SYS_150_PREFIX: ./llvm

defaults:
  run:
    working-directory: ./takoc

jobs:
  takoc:
    name: Takoc Test, build and lint using ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v2
      with:
        path: |
          C:/Program Files/LLVM
          ./llvm
        key: llvm-15.0
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "15.0"
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
    - name: Check llvm path
      run: "echo $LLVM_SYS_150_PREFIX; ls $LLVM_SYS_150_PREFIX"
    - name: Run tests
      run: cargo test --locked --release --verbose
    - name: Run ignored tests
      run: cargo test --locked --release --verbose -- --ignored
    - name: Build
      run: cargo build --locked --release --verbose
    - name: Upload executable Linux
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v1
      with:
        name: takoc
        path: ./target/release/takoc
    - name: Upload executable Windows
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v1
      with:
        name: takoc.exe
        path: ./target/release/takoc.exe
    - name: Install clippy
      run: rustup component add clippy
    - name: Clippy takolib
      run: cargo clippy --all-features -- -D warnings
    - name: Clippy takoc
      run: cargo clippy --all-features -- -D warnings
    - name: Install fmt
      run: rustup component add rustfmt
    - name: Format
      run: cargo fmt --all -- --check
