name: Check tako-webui

on: [push]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./tako-webui

jobs:
  check_webui:
    name: Check webui using ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          /home/runner/.cargo/
          target
        key: ${{ runner.os }}-webui-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-webui-cargo-${{ hashFiles('**/Cargo.lock') }}
          ${{ runner.os }}-webui-cargo-
          ${{ runner.os }}-
    - name: install wasm toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
        profile: minimal
    - name: Install trunk
      uses: jetli/trunk-action@v0.1.0
      with:
        version: 'latest'
    - name: Build webui
      run: trunk build
    - name: Run webui tests
      run: cargo fmt --all -- --check
