name: takolib

on: [push]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: takolib

jobs:
  takolib:
    name: takolib CI ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install missing libs
      run: "wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb ; sudo dpkg -i libtinfo5_6.3-2ubuntu0.1_amd64.deb"
    - uses: actions/cache@v3
      with:
        path: |
          /home/runner/.cargo/
          target
        key: ${{ runner.os }}-takolib-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-takolib-cargo-${{ hashFiles('**/Cargo.lock') }}
          ${{ runner.os }}-takolib-cargo-
          ${{ runner.os }}-
    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: |
          C:/Program Files/LLVM
          ./llvm
        key: llvm-18.1
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "18.1.4"
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
    - name: Setup LLVM_PATH
      run: "echo \"LLVM_SYS_181_PREFIX=$LLVM_PATH\" >> $GITHUB_ENV"
    - name: Check llvm path
      run: "echo \"LLVM_PATH: $LLVM_PATH\"; echo \"LLVM_SYS_181_PREFIX: $LLVM_SYS_181_PREFIX\"; ls $LLVM_SYS_181_PREFIX; $LLVM_SYS_181_PREFIX/bin/llvm-config --version"
    - name: Run tests
      run: cargo test --locked --release --verbose
    - name: Run ignored tests
      run: cargo test --locked --release --verbose -- --ignored
    - name: Build
      run: cargo build --locked --release --verbose
    - name: Install clippy
      run: rustup component add clippy
    - name: Clippy
      run: cargo clippy --all-features -- -D warnings
    - name: Install fmt
      run: rustup component add rustfmt
    - name: Format
      run: cargo fmt --all -- --check
